apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:f95e4f1454deca015390b9dcdd875d58fa36a9ef4228f1794bc6cdb9376cf1ad
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
- digest: sha256:667c2d7d46059f815e977b40f7b44fce68617c1686dfd7b2e669c3850f32376b
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
